-- 0008_recruitment.sql
-- Menu Recruitment: port dari "Dashboard Recruitment Sproutlab.html" ke Supabase.
-- Pipeline 7 tahap, outcome 4, data kandidat lengkap. Akses dipisah di UI via password.

create sequence if not exists public.recruitment_cand_seq;
create sequence if not exists public.recruitment_agent_seq;

-- Generator kode aman dari race condition (dipanggil dari server via RPC).
create or replace function public.recruitment_next_code()
returns text language sql security definer set search_path = public as $$
  select 'CND-' || lpad(nextval('public.recruitment_cand_seq')::text, 4, '0');
$$;

create or replace function public.recruitment_next_agent_code()
returns text language sql security definer set search_path = public as $$
  select 'AGT-' || lpad(nextval('public.recruitment_agent_seq')::text, 4, '0');
$$;

create table public.recruitment_candidates (
  id              uuid primary key default gen_random_uuid(),
  code            text not null unique,
  name            text not null,
  whatsapp        text not null,
  email           text,
  domisili        text,
  birth           date,
  marital         text,
  education       text,
  jurusan         text,
  universitas     text,
  sales_exp       text,
  experience      text,
  cv_note         text,
  source          text,
  jalur           text,
  stage           text not null default 'sourcing'
                    check (stage in ('sourcing','screening','followup','interview_hr','interview_alfred','onboarding','agent')),
  outcome         text not null default 'active'
                    check (outcome in ('active','talent_pool','tidak_lolos','agent_aktif')),
  max_reached     int  not null default 0,
  archived        boolean not null default false,
  date_in         date not null default current_date,
  stage_since     date,
  last_updated    date,
  -- follow up
  interest        text,
  follow_note     text,
  last_contact    date,
  next_follow_up  date,
  -- interview (interview_at disimpan sbg string datetime-local lokal, hindari geser timezone)
  interview_at    text,
  interview_done  boolean not null default false,
  score_hr        int,
  note_hr         text,
  rec_hr          text,
  note_alfred     text,
  -- onboarding / kontrak
  docs            jsonb not null default '{}'::jsonb,
  doc_link        text,
  join_date       date,
  contract_status text,
  contract_link   text,
  -- agent
  agent_code      text,
  agent_status    text,
  -- lain
  history         jsonb not null default '[]'::jsonb,
  created_at      timestamptz not null default now()
);

create unique index recruitment_candidates_whatsapp_key on public.recruitment_candidates (whatsapp);
create index recruitment_candidates_stage_idx   on public.recruitment_candidates (stage);
create index recruitment_candidates_outcome_idx on public.recruitment_candidates (outcome);

alter table public.recruitment_candidates enable row level security;

-- Pemisah akses nyata ada di UI (password Sabina26). Di level DB: semua user login boleh akses.
create policy "recruitment_select" on public.recruitment_candidates for select
  using (auth.uid() is not null);
create policy "recruitment_insert" on public.recruitment_candidates for insert
  with check (auth.uid() is not null);
create policy "recruitment_update" on public.recruitment_candidates for update
  using (auth.uid() is not null) with check (auth.uid() is not null);
create policy "recruitment_delete" on public.recruitment_candidates for delete
  using (auth.uid() is not null);

-- ============ SEED: kandidat asli dari Glints ============
insert into public.recruitment_candidates
  (code, name, whatsapp, email, domisili, birth, marital, education, jurusan, universitas, sales_exp, experience, cv_note, source, jalur, stage, outcome, max_reached, date_in, stage_since, last_updated, next_follow_up, interview_at, history)
values
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Annisa Novrianty', '6283805831659', 'a.novrianty10@gmail.com', 'Depok, Jawa Barat', '1998-11-10', 'Menikah', 'S1', 'Manajemen Keuangan', 'Universitas Pamulang', 'Ya', '8+ thn telemarketing & Tele Financial Advisor asuransi (Sunlife, Ciputra Life, BCA Life 2017-2026); banyak award sales, APE 235jt', 'Glints — Insurance Advisor', 'Glints', 'Prohire Prudential', 'screening', 'active', 1, '2026-06-09', '2026-06-09', '2026-06-09', null, null, '[{"d":"09 Jun","t":"Screening hub: skor 88 — rekomendasi Prohire Prudential (kandidat terkuat; konfirmasi income saat pre-qual)"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Vero Okka Nugroho', '6282213219112', 'verookkanugroho@gmail.com', 'Tangerang, Banten', null, null, 'S1', 'Ilmu Hukum', 'Universitas Muhammadiyah Tangerang', 'Ya', '±7 thn marketing/sales — agen asuransi, account manager, telemarketing, sales lapangan (Proline Finance, Mega Central Finance)', 'Glints — Insurance Advisor', 'Glints', 'Prohire Sprout', 'screening', 'active', 1, '2026-06-09', '2026-06-09', '2026-06-09', null, null, '[{"d":"09 Jun","t":"Screening hub: skor 66 — rekomendasi Prohire Sprout (CV agak umum, gali detail saat wawancara)"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Zikri Fadli Akbar', '6283182102935', 'zikrifadliakbar@gmail.com', 'Jakarta Barat', null, null, 'S1', 'Manajemen', 'Universitas Dharma Andalas', 'Tidak', 'Fresh grad S1 Manajemen; magang admin/sekretariat Dinas Perkimtan Sumbar; minat literasi keuangan (GenBI, pasar modal syariah)', 'Glints — Insurance Advisor', 'Glints', 'Prohire Sprout', 'interview_hr', 'active', 3, '2026-06-09', '2026-06-09', '2026-06-09', null, '2026-06-09T19:00', '[{"d":"09 Jun","t":"Screening hub: skor 54 — borderline (jalur tentatif Prohire Sprout), finalkan saat wawancara"},{"d":"09 Jun","t":"Wawancara dijadwalkan hari ini pukul 19:00"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Dinita Salsabila', '6285945532015', 'dinisalsaa@gmail.com', 'Ciamis, Jawa Barat', '2004-01-11', 'Belum menikah', 'D3', 'Kebidanan', 'Poltekkes Kemenkes Tasikmalaya', 'Tidak', 'Bidan (D3 Kebidanan, IPK 3.73); pengalaman klinis kebidanan; belum ada pengalaman sales/asuransi', 'Glints — Insurance Advisor', 'Glints', 'Freelance', 'screening', 'active', 1, '2026-06-09', '2026-06-09', '2026-06-09', null, null, '[{"d":"09 Jun","t":"Screening hub: skor 30 — Tidak Disarankan (D3 di bawah gate S1, tanpa pengalaman sales, luar Jabodetabek); jalur Freelance tentatif"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Ilham Budiansyah', '6282125116215', 'ilhambdsh@gmail.com', 'Sukabumi, Jawa Barat', null, null, 'S1', 'Ekonomi Syariah', 'STIE Gasantara Sukabumi', 'Ya', '±1,5 thn sales/marketing — Agen Asuransi (Heksa Solutions Insurance, 2025-2026), sales lapangan wifi (Bali Towerindo), sales marketing Mitsubishi; sebelumnya aviation security', 'Glints — Insurance Advisor', 'Glints', 'Prohire Sprout', 'screening', 'active', 1, '2026-06-09', '2026-06-09', '2026-06-09', null, null, '[{"d":"09 Jun","t":"Screening hub: skor 64 — rekomendasi Prohire Sprout (pengalaman agen asuransi + sales kuat; catatan: domisili Sukabumi/luar Jabodetabek)"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Muhammad Daffa Al Alif', '6281275101529', 'daffaalalif06@gmail.com', 'Simpang Empat, Sumatera Barat', null, null, 'S1', 'Sistem Informasi', 'Universitas Putra Indonesia YPTK Padang', 'Tidak', 'Fresh grad S1 Sistem Informasi (GPA 3.40); magang IT Support RS Otak Bukittinggi; latar IT/web, belum ada pengalaman sales', 'Glints — Insurance Advisor', 'Glints', null, 'screening', 'active', 1, '2026-06-09', '2026-06-09', '2026-06-09', null, null, '[{"d":"09 Jun","t":"Screening hub: skor 40 — borderline/Tidak Disarankan (latar IT tanpa pengalaman sales, domisili Sumatera Barat/luar Jabodetabek); jalur belum ditentukan"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Muhammad Aldryan Savchenko', '6289613786100', 'aldryansvchnko@email.com', 'Bengkulu', null, null, 'S1', 'Agribisnis', 'Universitas Bengkulu', 'Tidak', 'Fresh grad S1 Agribisnis (IPK 3,70 Cum Laude); kuat di socio-entrepreneurship, pengembangan UMKM, digital marketing, riset & kepemimpinan organisasi; peneliti terpublikasi + co-author buku. Belum ada pengalaman sales langsung', 'Glints — Insurance Advisor', 'Glints', 'Freelance', 'interview_hr', 'active', 3, '2026-06-09', '2026-06-09', '2026-06-09', null, '2026-06-10T13:00', '[{"d":"09 Jun","t":"Screening hub: skor 60 — Freelance (min S1 terpenuhi; soft skill/entrepreneurship/komunikasi kuat; belum ada pengalaman sales, luar Jabodetabek)"},{"d":"09 Jun","t":"Bersedia ditawarkan jalur Freelance; wawancara dijadwalkan besok (10 Jun) pukul 13:00"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Maria Simarmata', '6285668783002', 'mariafalentinasimarmata@gmail.com', 'Jakarta', null, null, 'S1', 'Pendidikan Bahasa Inggris', 'Universitas Prima Indonesia', 'Tidak', 'Fresh grad S1 Pendidikan Bahasa Inggris (GPA 3.73); guru bahasa Inggris (2024) + magang Administration Support/Underwriter di PT Asuransi Kredit Indonesia (eksposur industri asuransi); aktif Kampus Mengajar & student exchange. Belum ada pengalaman sales langsung', 'Glints — Insurance Advisor', 'Glints', null, 'screening', 'active', 1, '2026-06-09', '2026-06-09', '2026-06-09', null, null, '[{"d":"09 Jun","t":"Screening hub: skor 58 — rekomendasi Freelance (min S1; domisili Jakarta/Jabodetabek, ada eksposur asuransi via magang underwriter, komunikasi/teaching kuat; belum ada pengalaman sales)"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Herdi Wijaya', '6283815852782', 'herd.wijayaa@gmail.com', 'Jakarta Selatan', null, null, 'SMA/SMK', 'IPS', 'SMA Darul Falah Bandung', 'Tidak', '4 thn Personal Assistant & Administration di Vision Corporation (PT Asuransi Allianz Life Indonesia) — klaim, SPAJ, administrasi polis, reminder lisensi agen; paham proses & produk asuransi. Latar admin (bukan sales langsung)', 'Glints — Insurance Advisor', 'Glints', null, 'followup', 'active', 2, '2026-06-10', '2026-06-10', '2026-06-10', '2026-06-13', null, '[{"d":"10 Jun","t":"Screening hub: skor 50 — borderline. Plus: 4 thn di industri asuransi (admin Allianz, paham produk/proses) + domisili Jakarta. Minus: pendidikan SMA (di bawah gate Freelance S1) & latar admin bukan sales. Jalur belum ditentukan"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Natasha', '6285693153522', 'natanartasha@gmail.com', 'Jakarta Barat', null, null, 'SMA/SMK', 'Administrasi Perkantoran', 'SMK Perti', 'Tidak', 'Fresh grad SMK Administrasi Perkantoran (2025); pengalaman admin/PKL, customer service & retail (barista all-rounder, sales retail singkat). Entry-level, belum ada pengalaman sales/asuransi', 'Glints — Insurance Advisor', 'Glints', null, 'screening', 'active', 1, '2026-06-10', '2026-06-10', '2026-06-10', null, null, '[{"d":"10 Jun","t":"Screening hub: skor 32 — Tidak Disarankan (SMK di bawah gate S1, sangat junior/fresh grad, belum ada pengalaman sales berarti; plus: domisili Jakarta). Pertimbangkan kembali"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Yohanes Setiawan', '6287751962728', 'yohanessetiawan705@gmail.com', 'Jakarta Barat (mengajar; asal Lampung)', null, null, 'S1', 'Pendidikan Fisika', 'Universitas Lampung', 'Ya', 'S1 Pendidikan Fisika (IPK 3,84); guru/tutor + Marketing Team Primagama (sosialisasi/promosi program ke sekolah). Komunikasi & public speaking kuat. Belum jual asuransi', 'Glints — Insurance Advisor', 'Glints', null, 'screening', 'active', 1, '2026-06-10', '2026-06-10', '2026-06-10', null, null, '[{"d":"10 Jun","t":"Screening hub: skor 62 — layak. Plus: S1, komunikasi/public speaking kuat, ada pengalaman marketing (Primagama). Catatan: konfirmasi domisili (asal Lampung, mengajar di Jakarta). Jalur finalkan saat wawancara"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Raissa Marsha Huwaina', '6281111777191', 'raissamarsha@gmail.com', 'Bandung', null, null, 'S1', 'Manajemen', 'Telkom University', 'Ya', 'S1 Manajemen; Independent Consultant (sales & consultation, rekrut/mentor partner, target & bonus) + peran manajerial/HR/recruiter di Restu Maryam Group. Ada pengalaman sales & rekrut', 'Glints — Insurance Advisor', 'Glints', 'Prohire Sprout', 'screening', 'active', 1, '2026-06-10', '2026-06-10', '2026-06-10', null, null, '[{"d":"10 Jun","t":"Screening hub: skor 60 — Prohire Sprout (ada pengalaman sales/konsultan + rekrutmen). Catatan: domisili Bandung (luar Jabodetabek) — konfirmasi kesediaan Jabodetabek/relokasi"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Ummi Hafilda', '6287881270642', 'hafildaaummi@gmail.com', 'Tangerang', null, null, 'S1', 'Akuntansi', 'Universitas Muhammadiyah Tangerang', 'Tidak', 'S1 Akuntansi (IPK 3,65); 4+ thn Accounting & Tax / Finance / Purchasing. Profesional, teliti. Belum ada pengalaman sales/asuransi', 'Glints — Insurance Advisor', 'Glints', null, 'screening', 'active', 1, '2026-06-10', '2026-06-10', '2026-06-10', null, null, '[{"d":"10 Jun","t":"Screening hub: skor 56 — profesional S1 (akuntansi), domisili Tangerang. Career-switcher: belum ada pengalaman sales — gali minat & aptitude sales saat wawancara. Jalur belum ditentukan"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Cindy Aisyah Putri Hartoyo', '6281298441245', 'cindyaisyahputrihartoyo@gmail.com', 'Bekasi', null, null, 'S1', 'Sosial Ekonomi Perikanan', 'Universitas Brawijaya', 'Tidak', 'S1 (IPK 3,84); admin product & operations di perusahaan teknologi; organisasi kuat. Belum ada pengalaman sales/asuransi', 'Glints — Insurance Advisor', 'Glints', 'Freelance', 'screening', 'active', 1, '2026-06-10', '2026-06-10', '2026-06-10', null, null, '[{"d":"10 Jun","t":"Screening hub: skor 54 — Freelance (S1, Bekasi/Jabodetabek, organisasi & teliti). Belum ada pengalaman sales — minat sales digali saat wawancara"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Muhammad Rizaldi', '6287888646416', 'muhammad.rizaldi324@gmail.com', 'Jakarta Barat (Palmerah)', null, null, 'S1', 'Manajemen', 'BINUS University', 'Tidak', 'S1 Manajemen (BINUS); event organizer (Jobs Expo), freelance ekspedisi JNE, admin; koordinator komunitas. Belum ada pengalaman sales/asuransi', 'Glints — Insurance Advisor', 'Glints', 'Freelance', 'screening', 'active', 1, '2026-06-10', '2026-06-10', '2026-06-10', null, null, '[{"d":"10 Jun","t":"Screening hub: skor 50 — Freelance (S1, Jakarta). Latar event/admin, belum ada pengalaman sales. Borderline-layak"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Alfie Hafiz', '6282123933603', 'hafizalfie77@gmail.com', 'Kab. Karawang, Jawa Barat', null, null, 'S1', 'Pariwisata', 'Universitas Sahid', 'Tidak', 'S1 Pariwisata; 8 thn distribusi/agen pengiriman logistik (PT Sadikun BBM), karyawan terbaik 2019. Customer service & loyal, tapi bukan sales/asuransi', 'Glints — Insurance Advisor', 'Glints', null, 'screening', 'active', 1, '2026-06-10', '2026-06-10', '2026-06-10', null, null, '[{"d":"10 Jun","t":"Screening hub: skor 48 — borderline. Plus: loyalitas & customer service. Minus: domisili Karawang (luar Jabodetabek) & belum ada pengalaman sales. Konfirmasi domisili"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Rifqi Afif', '6285260277166', 'rifqiafif321@gmail.com', 'Medan / belum jelas', '2000-10-30', 'Belum menikah', 'S1', 'Penerbangan (D3) / S1 Suryadarma', 'Universitas Suryadarma; D3 Poltekbang Medan', 'Tidak', 'D3 Penerbangan + S1; pengalaman instansi pemerintah bidang penerbangan (verifikasi dokumen, monitoring). Teknis/operasional, belum ada pengalaman sales', 'Glints — Insurance Advisor', 'Glints', null, 'screening', 'active', 1, '2026-06-10', '2026-06-10', '2026-06-10', null, null, '[{"d":"10 Jun","t":"Screening hub: skor 45 — borderline. Latar teknis penerbangan, belum ada pengalaman sales; domisili belum jelas (Medan/Aceh?) — konfirmasi"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Hanna Sytha Kamilia', '6281315898977', 'hannasythakamilia@gmail.com', 'Jakarta (rencana kuliah di Belanda)', null, null, 'SMA/SMK', '-', 'Labschool Jakarta (calon Univ of Groningen)', 'Tidak', 'Lulusan SMA berprestasi; founder startup, magang digital marketing, banyak sertifikasi finance, multibahasa. Sangat menjanjikan TAPI rencana kuliah S1 di Belanda', 'Glints — Insurance Advisor', 'Glints', null, 'screening', 'active', 1, '2026-06-10', '2026-06-10', '2026-06-10', null, null, '[{"d":"10 Jun","t":"Screening hub: skor 40 — profil mengesankan tapi MISMATCH: masih SMA (di bawah gate S1) & berencana kuliah di Belanda (tidak menetap di Jabodetabek). Pertimbangkan kembali / freelance jangka pendek jika dia mau"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Aqilla Nurul Azizah', '6289506589096', 'aqillaazizah91@gmail.com', 'Jakarta (kampus ITPLN)', null, null, 'S1', 'Teknik Informatika (sedang kuliah)', 'Institut Teknologi PLN', 'Tidak', 'Mahasiswa Teknik Informatika (baru mulai 2025); magang digital marketing kafe (2 bln), aktif OSIS. Sangat junior, belum lulus, belum ada pengalaman sales', 'Glints — Insurance Advisor', 'Glints', null, 'screening', 'active', 1, '2026-06-10', '2026-06-10', '2026-06-10', null, null, '[{"d":"10 Jun","t":"Screening hub: skor 40 — kurang disarankan: mahasiswa baru (belum S1), sangat junior, belum ada pengalaman sales. Plus: domisili Jakarta. Hanya jika tunjukkan motivasi sales kuat"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Jullia Wulandari', '6281367016654', 'julliawulandari77@gmail.com', 'Bandar Lampung', null, null, 'S1', 'Manajemen (sedang kuliah, Univ Terbuka)', 'Universitas Terbuka', 'Tidak', 'Sedang S1 Manajemen (UT, belum lulus); admin stock + chief cashier (retail). Customer service, belum ada pengalaman sales/asuransi', 'Glints — Insurance Advisor', 'Glints', null, 'screening', 'active', 1, '2026-06-10', '2026-06-10', '2026-06-10', null, null, '[{"d":"10 Jun","t":"Screening hub: skor 38 — kurang disarankan: kuliah belum selesai, domisili Lampung (luar Jabodetabek), belum ada pengalaman sales"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Nava Azzahra', '6282288131771', 'navaazzahra811@gmail.com', 'Jakarta Timur', null, null, 'S1', 'Akuntansi (sedang kuliah)', 'STIE Indonesia Jakarta', 'Tidak', 'Mahasiswa Akuntansi (baru mulai 2025), aktif HIMA; belum ada pengalaman kerja/sales', 'Glints — Insurance Advisor', 'Glints', null, 'screening', 'active', 1, '2026-06-10', '2026-06-10', '2026-06-10', null, null, '[{"d":"10 Jun","t":"Screening hub: skor 35 — kurang disarankan: mahasiswa baru (belum S1), belum ada pengalaman kerja/sales. Plus: domisili Jakarta Timur"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Fathiatur Rohmah', '62895376416889', 'fathiatur.17@gmail.com', 'Jakarta (UIN Jkt / magang BSI Pondok Indah)', null, null, 'S1', 'Manajemen Dakwah — Lembaga Keuangan Syariah', 'UIN Syarif Hidayatullah Jakarta', 'Tidak', 'S1 (semester akhir, IPK 3,69); magang Customer Service & Admin di Bank Syariah Indonesia — edukasi & konsultasi produk perbankan syariah ke nasabah, komunikasi persuasif, manajemen komplain. Adjacent ke advisory, belum sales langsung', 'Glints — Insurance Advisor', 'Glints', 'Freelance', 'screening', 'active', 1, '2026-06-10', '2026-06-10', '2026-06-10', null, null, '[{"d":"10 Jun","t":"Screening hub: skor 60 — layak (Freelance). Plus: S1 + latar lembaga keuangan syariah, edukasi/konsultasi produk & komunikasi persuasif (relevan ke advisory), domisili Jakarta. Catatan: belum lulus (semester akhir), belum sales langsung; verifikasi nomor WA (format tampak ada digit berlebih)"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Syahrul Eko Ramadan', '62895385897206', 'syahruleko206@gmail.com', 'Karawang', null, null, 'S1', 'Pendidikan Jasmani (PJKR)', 'Universitas Pendidikan Indonesia', 'Tidak', 'S1 PJKR (IPK 3,4); coach rugby, guru PJOK, atlet rugby berprestasi (medali Porda Jabar). Disiplin, kompetitif, kepemimpinan & komunikasi kuat. Belum ada pengalaman sales/asuransi', 'Glints — Insurance Advisor', 'Glints', null, 'screening', 'active', 1, '2026-06-10', '2026-06-10', '2026-06-10', null, null, '[{"d":"10 Jun","t":"Screening hub: skor 47 — borderline. Plus: disiplin & jiwa kompetitif atlet/coach, kepemimpinan & komunikasi (potensi sales bagus). Minus: domisili Karawang (luar Jabodetabek) & belum ada pengalaman sales. Konfirmasi domisili/kesediaan Jabodetabek"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Poppy Weldrika Setligt', '6285159962557', 'poppyweldrika0801@gmail.com', 'Jakarta', null, null, 'D3', 'Sekretari Manajemen', 'STIE Indonesia Pontianak', 'Ya', '18+ thn telemarketing & sales asuransi: BCA Life (Associate Telemarketing Manager 2018-now), AXA Mandiri (Supervisor), Cigna, HSBC. Pimpin & coaching tim, banyak award (Best Telemarketing BCA Life 2020-2024, SPV terbaik APE). Leadership + sales sangat kuat', 'Glints — Insurance Advisor', 'Glints', 'Prohire Prudential', 'screening', 'active', 1, '2026-06-10', '2026-06-10', '2026-06-10', null, null, '[{"d":"10 Jun","t":"Screening hub: skor 90 — SANGAT KUAT, prioritaskan. 18+ thn sales asuransi + manajemen tim (BCA Life, AXA Mandiri, Cigna, HSBC), banyak award. Domisili Jakarta. Catatan: pendidikan D3 (di bawah gate S1 FLP) tapi pengalaman luar biasa -> Prohire Prudential; potensi leader-track"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Angel Elisabet', '6288214133049', 'angelelisabet03@gmail.com', 'Jakarta', null, null, 'S1', 'Pendidikan Bahasa Inggris', 'Universitas MH Thamrin', 'Tidak', 'S1 English Education (lulus 2025); Supervisor Kopi Kenangan (operasional, handling komplain, customer loyalty), admin PT KAI Logistik, guru. Customer-facing & supervisory; belum ada pengalaman sales/asuransi', 'Glints — Insurance Advisor', 'Glints', 'Freelance', 'screening', 'active', 1, '2026-06-10', '2026-06-10', '2026-06-10', null, null, '[{"d":"10 Jun","t":"Screening hub: skor 52 — Freelance (S1, domisili Jakarta, pengalaman supervisory & customer-facing). Belum ada pengalaman sales — gali minat sales saat wawancara"}]'::jsonb),
  ('CND-' || lpad(nextval('public.recruitment_cand_seq')::text,4,'0'), 'Melisandi Telaumbanua', '6281396528879', 'lisatelaumbanua16@gmail.com', 'Gunungsitoli, Nias (Sumut)', null, null, 'S1', 'Pendidikan Bahasa Inggris', 'Universitas Nias', 'Tidak', 'S1 Pend. Bahasa Inggris (IPK 3,37); staff admin kantor desa, PKL; kuat di kepemimpinan event/organisasi (Manager Indonesian Music Expo Bali, Direktur Festival — kelola anggaran & koordinasi), komunikasi & Inggris baik. Belum ada pengalaman sales/asuransi', 'Glints — Insurance Advisor', 'Glints', null, 'screening', 'active', 1, '2026-06-10', '2026-06-10', '2026-06-10', null, null, '[{"d":"10 Jun","t":"Screening hub: skor 44 — borderline. Plus: komunikasi & kepemimpinan event kuat, S1. Minus: domisili Gunungsitoli/Nias (jauh dari Jabodetabek) & belum ada pengalaman sales. Konfirmasi domisili/kesediaan"}]'::jsonb)
on conflict (whatsapp) do nothing;
